### ISSUE TITLE
Open Intervals aren't synced

### ISSUE THREAD

**Issue by Akendo** [timewarrior-synchronize/timew-sync-client#50]
When the sync is in process, a running process will *not* be tracked. This seems a little bit like a flaw.

**Comment by janbormet** [comment]
Hey, I can remember that we discussed this thoroughly before deciding not to sync open intervals.

When you tried to sync an open interval, the only reason for doing this (instead of waiting with syncing this interval until its closed) would be to replicate the open interval to other clients. This is only inviting conflicts though. Timewarrior does not really support tracking of concurrent intervals. If you start tracking for tag X (`timew start X`) and then start tracking for tag X again, it will just ignore the second `timew start X`. If you start tracking for X first (`timew start X`) and then later track for tag Y (`timew start Y`) it closes the interval for X, then starts tracking Y. 
In general, timewarrior does not allow for tracking-intervals to overlap. If you synchronized an open interval, you would inevitably close it at different times on different clients. This conflict would then have to be solved by the server once you syncronize those intervals with conflicting end-times anyways. 
So the only scenario I can think of where you would want to sync an open interval is when you would move all your time-tracking data from one client to another including the currently tracked process - *and never use the old client again* (e.g. once you switch to a new laptop) because otherwise you would run into conflicts. If you really do not want to end the old tracking, I would advise to just copy the `data` folder (or even the entire `.timewarrior` folder) to your new machine. If I remember correctly, you could also just ignore the currently tracked process, sync and then start tracking again on your new machine, beginning from the original start-time.

I hope this clarifies it!
If you see another reasonable usecase for syncing running tracked processes, I'd love to hear them!
Kind regards
Jan

**Comment by janbormet** [comment]
Btw: I think we also considered closing the active tracking, then syncing, then starting it again, but we agreed that just ignoring it until it is stopped is the better solution, as it does not change any tracking semantics (like splitting a tracking into two seperate ones, even if they sum up to the original length).

**Comment by arneturuc** [comment]
A bit late but I want to clarify that running processes will only get split, without any real delay.
I have modified the notification slightly, as to reduce confusion here.
Thank you for pointing that out!
